apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-promtail
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: https://grafana.github.io/helm-charts
    chart: promtail
    targetRevision: 6.15.0
    helm:
      valueFiles:
      - $values/monitoring/promtail/values.yaml
  - repoURL: https://github.com/automatewithcharan/observability.git
    targetRevision: main
    ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
