apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-kube-prometheus-stack
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 62.3.0
    helm:
      valueFiles:
      - $values/monitoring/kube-prometheus-stack/values-base.yaml
      - $values/monitoring/kube-prometheus-stack/values-prod.yaml
  - repoURL: https://github.com/automatewithcharan/observability.git
    targetRevision: main
    ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
